sitename: Adam Pritchard
sitedescription: coder, etc.
titleprefix: adam-p

navigation:
- text: Home
  url: /
  name: home
- text: Projects
  url: /projects/
  name: projects
- text: Résumé
  url: /resume/
  name: resume
- text: Contact
  url: /contact/
  name: contact
